version: '3.8'

services:
  # SvelteKit frontend for development
  frontend:
    build:
      context: ./clamav-sveltekit
      dockerfile: Dockerfile.dev
    container_name: clamav-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"  # Dev server port
    environment:
      - NODE_ENV=development
      # Fix for Node.js crypto in Docker
      - NODE_OPTIONS=--experimental-vm-modules
    volumes:
      - ./clamav-sveltekit:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - api
    networks:
      - clamav-network

  # Go REST API server
  api:
    build:
      context: ./clamav-server
      dockerfile: Dockerfile
    container_name: clamav-api-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - CLAMD_ADDRESS=clamd:3310
    depends_on:
      - clamd
    networks:
      - clamav-network

  # ClamAV daemon as a sidecar
  clamd:
    image: clamav/clamav:latest
    platform: linux/amd64
    container_name: clamd-dev
    restart: unless-stopped
    ports:
      - "3310:3310"
    environment:
      - CLAMD_TCP_ADDR=0.0.0.0
      - CLAMD_TCP_PORT=3310
    healthcheck:
      test: ["CMD", "clamdscan", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - clamav-network

# Define a network for the services to communicate
networks:
  clamav-network:
    driver: bridge 